config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  get 'welcome/sportpicks'

  get 'welcome/fantasty'

  get 'welcome/about'

  get 'welcome/subscription'

  root 'places#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	def index
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :authenticate_user!

  def index
  end

  def sportpicks

  end

  def fantasty
  end

  def about
  end

  def subscription
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Haymakerbets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Beginning Of Navigation Bar -->
			<header id="header" class="alt">
				<h1><strong><a href="index.html">HaymakerBets</a></strong>.com</h1>
				<nav id="nav">
					<ul>
						<li><%= link_to "HOME", root_path %></li>

						<li><%= link_to "SPORT PICKS", welcome_sportpicks_path %></li>


						<li><%= link_to "Software Name", welcome_subscription_path %></li>
						

						      <% if user_signed_in? %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>

					</ul>
				</nav>
			</header>

			<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>
<!-- End Of Navigation Bar-->

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</body>
</html>

app/views/places/index.html.erb
<!DOCTYPE HTML>
<!--
	Spatial by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>HaymakerBets.com</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="landing">

		<!-- Banner -->
			<section id="banner">
				<h2>Haymaker Bets</h2>
				<p>Sport Picks & Fantasy Lineups <br /> By Professional Sport Anaylyst & Software.</p>
				<ul class="actions">
					<li><a href="#" class="button special big">SIGN UP</a></li>
				</ul>
			</section>

			<!-- One -->
				<section id="one" class="wrapper style1">
					<div class="container 75%">
						<div class="row 200%">
							<div class="6u 12u$(medium)">
								<header class="major">
									<h2>Picks Everyday!</h2>
									<p>Multiple Sports!</p>
								</header>
							</div>
							<div class="6u$ 12u$(medium)">
								<p>Whether you're wondering whose going to win the footbal game today, or trying to decide how if you're MLB team will make it to the World Series, this is the place for you!</p>
								<p>We share our favorite picks of the day, and even share our daily fantasty lineups on DraftKings and FanDuel!</p>
							</div>
						</div>
					</div>
				</section>

			<!-- Two -->
				<section id="two" class="wrapper style2 special">
					<div class="container">
						<header class="major">
							<h2>Title GOES RIGHT HERE</h2>
							<p>SUB TITLE RIGHT BELOW HERE</p>
						</header>
						<div class="row 150%">
							<div class="6u 12u$(xsmall)">
								<div class="image fit captioned">
								<a href="">
									<img src="assets/lebron.jpg" /> 
								</a>
									<h3>Click Here For Pick of The Day!</h3>
								</div>
							</div>
							<div class="6u$ 12u$(xsmall)">
								<div class="image fit captioned">
									<a href="">
										<img src="assets/overeem.jpg"/>
									</a>
									<h3>Click Here For Today's Fantasty Lineup!</h3>
								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Three -->
				<section id="three" class="wrapper style1">
					<div class="container">
						<header class="major special">
							<h2>HAYMAKER LOGO HERE</h2>
							<p>Make sure to follow our social media!</p>
						</header>
						<div class="feature-grid">
							<div class="feature">

								<a href="https://twitter.com/HaymakerBets">
								<div class="image rounded"><img src="assets/twitter1.png"/></div>
								</a>

								<div class="content">
									<header>
										<h4>Twitter</h4>
										<p>Follow us!</p>
									</header>
									<p>Paragraph about it Paragraph about it Paragraph about it Paragraph about it Paragraph about it</p>
								</div>
							</div>
							<div class="feature">

								<a href="https://www.facebook.com/groups/501987903307127/">
								<div class="image rounded"><img src="assets/facebook1.png"/></div>
								</a>

								<div class="content">
									<header>
										<h4>Facebook</h4>
										<p>JOIN OUR GROUP DISCUSSION!</p>
									</header>
									<p>Paragraph about it Paragraph about it Paragraph about it Paragraph about it Paragraph about it</p>
								</div>
							</div>
							<div class="feature">

								<a href="">
								<div class="image rounded"><img src="assets/youtube1.png"/></div>
								</a>

								<div class="content">
									<header>
										<h4>YouTube</h4>
										<p>Subscribe!</p>
									</header>
									<p>Paragraph about it Paragraph about it Paragraph about it Paragraph about it Paragraph about it</p>
								</div>
							</div>
							<div class="feature">

								<a href="">
								<div class="image rounded"><img src="assets/instagram1.png"/></div>
								</a>

								<div class="content">
									<header>
										<h4>Instagram</h4>
										<p>Follow us!</p>
									</header>
									<p>Paragraph about it Paragraph about it Paragraph about it Paragraph about it Paragraph about it</p>
								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Four -->
				<section id="four" class="wrapper style3 special">
					<div class="container">
						<header class="major">
							<h2>Aenean elementum ligula</h2>
							<p>SOMETHING END HERE</p>
						</header>
						<ul class="actions">
							<li><a href="#" class="button special big">Get in touch</a></li>
						</ul>
					</div>
				</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="#" class="icon fa-facebook"></a></li>
						<li><a href="#" class="icon fa-twitter"></a></li>
						<li><a href="#" class="icon fa-instagram"></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; HaymakerBets.com</li>
						<li>&copy; copyright2016@haymakerbets.com</li>
						<li>Contact us: HaymakerBets@gmail.com</li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/fantasty.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>HaymakerBets.com</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="landing">
	
<!-- #topmenu -->
<div class="topmenu">
</br></br></br>
</div>

app/views/welcome/sportpicks.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>HaymakerBets.com</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="landing">

<!-- #topmenu -->
<div class="topmenu">
</br></br></br>
</div>
<!-- Main -->
			<section id="main" class="wrapper">
				<div class="container">

					<header class="major special">
						<h2>Sport Picks Of The Day!</h2>
						<p>Current POTD Record: 1-0-0  (W/L/D)</p>
					</header>

					<a href="#" class="image fit"><img src="assets/soccer.jpg" alt="" /></a>
					
					<h2>Sport Pick 1</h2>

					<p>Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.  Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.</p>



					<h2>Sport Pick 2</h2>

					<p>Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.  Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.</p>


	
					<h2>Sport Pick 3</h2>

					<p>Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.  Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here. Do a sport pick analysis right here.</p>

				</div>
			</section>


							
					
	<h4>Left &amp; Right</h4>
	<p><span class="image left"><img src="images/pic04.jpg" /></span>Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup Software Model is da best yup software model is da best haha yup</p>

	</section>			

								



		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="#" class="icon fa-facebook"></a></li>
						<li><a href="#" class="icon fa-twitter"></a></li>
						<li><a href="#" class="icon fa-instagram"></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; HaymakerBets.com</li>
						<li>&copy; copyright2016@haymakerbets.com</li>
						<li>Contact us: HaymakerBets@gmail.com</li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/welcome/subscription.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>HaymakerBets.com</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="landing">
	
<!-- #topmenu -->
<div class="topmenu">
</br></br></br>
</div>

<%= simple_form_for @Subscriber do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>